name: gen_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  intl: ^0.17.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  flutter_mobx: ^2.0.6+4
  dartz: ^0.10.1
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  mobx_codegen: ^2.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/movies/